UPDATE `modules` SET `desc_module` = 'Le module de communication est la base du BUT MMI. La communication peut paraître assez “secondaire” mais elle est la base de tout projet. Que ce soit en audiovisuel, en développement ou en design, la communication est présente partout. Pourquoi voulez-vous communiquer? Comment voulez-vous communiquer? C’est grâce au module communication que vous allez pouvoir répondre à ces questions !' WHERE `modules`.`id_module` = 1;

UPDATE `modules` SET `desc_module` = 'Le module de développement web vous apprendra tout ce dont vous avez besoin pour créer un site web. HTML, CSS, JAVASCRIPT et PHP, sont tous les langages que vous apprendrez au sein du BUT MMI. Il n’y a pas de limite en ce qui concerne le développement, votre seule limite, c’est vous-même ! Alors laissez exploser votre créativité au sein de cette matière pour nous créer des sites web plus fous les uns que les autres !' WHERE `modules`.`id_module` = 2;

UPDATE `modules` SET `desc_module` = 'Le module de production audio et vidéo, vous apprendra énormément de choses. Que ce soit apprendre à utiliser une caméra, faire du montage, faire du motion design ou encore du sound design, les fans d’audiovisuel se feront un plaisir de découvrir cette matière avec des projets tout au long de l’année. Et ne vous en faites pas, en MMI on apprend tout de 0 !' WHERE `modules`.`id_module` = 3;

UPDATE `modules` SET `desc_module` = 'Le module UX&UI Design est LE module créatif du BUT MMI ! Vous voulez créer des affiches, faire des maquettes et bien plus encore? Ce module vous apprendra à rendre accessible et facile d’utilisation tous vos projets en les rendant le plus beau possible pour l’utilisateur ! Rien n’est impossible tant que vous avez de la créativité 😉' WHERE `modules`.`id_module` = 4;

UPDATE `modules` SET `desc_module` = 'Le module gestion de projet est l’un des modules les plus importants. Le travail en groupe est très présent au sein du BUT MMI, il est donc important de savoir comment bien s’organiser dans un groupe afin que le projet se passe le mieux possible. C’est ce que vous allez apprendre grâce à cette matière : la gestion du travail d’équipe !' WHERE `modules`.`id_module` = 5;

UPDATE `modules` SET `nom_module` = 'Production audiovisuelle et vidéo', `desc_module` = 'Le module de production audio et vidéo, vous apprendra énormément de choses. Que ce soit apprendre à utiliser une caméra, faire du montage, faire du motion design ou encore du sound design, les fans d’audiovisuel se feront un plaisir de découvrir cette matière avec des projets tout au long de l’année. Et ne vous en faites pas, en MMI on apprend tout de 0 !' WHERE `modules`.`id_module` = 6
